version: 0.0
os: linux
files:
        - source: /
          destination: /home/ubuntu/interactive-web-client
          overwrite: yes

permissions:
        - object: /home/ubuntu
          owner: ubuntu
          group: ubuntu
          mode: 755
hooks:
        BeforeInstall:
                - location: scripts/beforeInstall.bash
        AfterInstall:
                - location: scripts/afterInstall.bash
          
