import { IProject } from "../../types/base";

export const dummyProject: IProject = {
  id: 0,
  owner_id: 999,
  title: "test project",
  variables: {},
  pages: [
    {
      id: 0,
      name: "image & text page",
      projectId: 0,
      objects: [
        {
          id: 0,
          type: "image",
          name: "imageTest",
          isInteractive: false,
          positionX: 100,
          positionY: 100,
          width: 10,
          height: 20,
          zIndex: 5,
          opacity: 0.5,
          page_id: 1,
          imageSource: "/images/ex_ghost.png",
          isReversed: false,
          rotateDegree: 0,
        },
        {
          id: 1,
          type: "text",
          name: "textTest",
          isInteractive: false,
          positionX: 200,
          positionY: 200,
          width: 10,
          height: 20,
          zIndex: 5,
          opacity: 0.5,
          page_id: 1,
          textContent: "I am a ghost",
          fontSize: 16,
          fontFamily: "sans-serif",
          lineHeight: 24,
          letterSpacing: 0,
          color: "#000000",
          strokeWidth: 0,
          strokeColor: "#ffffff",
          backgroundColor: null,
          borderWidth: 0,
          borderColor: null,
        },
      ],
    },
    {
      id: 1,
      name: "empty page",
      projectId: 0,
      objects: [],
    },
  ],
  events: [],
};
