# This is a basic workflow to help you get started with Actions

name: Develop Branch Test

# Controls when the workflow will run
on:
  workflow_dispatch:
        
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request_target:
    branches:
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Repo checkout
        uses: actions/checkout@v3
        with:
          ref: develop

      # Runs a set of commands using the runners shell
      - name: Install Dependencies
        run: 
          yarn install
          
      - name: App Build
        run:
          npm run build
